#
# example balrog config
#
# the idea is to have a section for each part of the code
# currently there is a section for the MEDS making, which
# also determines how the data are downloaded
#
# we will have other sections for things like the galsim run,
# coadd making, etc.
#
meds_config:
    medsconf: "meds-balrog-test01"

    campaign: "y3a1_coadd"

    # we get the correct wcs from the null weight image headers
    use_astro_refine: False

    # extensions for single-epoch images
    # the ngwint files
    se_image_ext:  "sci"
    se_weight_ext: "wgt"
    se_bmask_ext:  "msk"

    # separate bkg files
    se_bkg_ext:    "sci"

    # separate seg files
    se_seg_ext:    "sci"

    # coadd images
    coadd_image_ext:  "sci"
    coadd_weight_ext: "wgt"
    coadd_bmask_ext:  "msk"

    # separate segmap file
    coadd_seg_ext:    "sci"

    # coadds are already background subtracted
    coadd_bkg_ext: "none"

    # DESDM prefers to have the compression keywords instead
    # of fpack command line arguments

    fpack_pars:
        FZQVALUE: 4
        FZTILE: "(10240,1)"
        FZALGOR: "RICE_1"
        # preserve zeros, don't dither them
        FZQMETHD: "SUBTRACTIVE_DITHER_2"
